/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(libs.org.jetbrains.kotlin.kotlin.reflect)
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    compileOnly(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    providedCompile(project(":language"))
    providedCompile(project(":util"))
    providedCompile(project(":theory"))
    providedCompile(project(":tableau"))
    providedCompile(project(":prover"))
    providedCompile(project(":inference"))
    providedCompile(project(":parser"))
}

description = "BITNOTS :: Common :: Tableau Prover"
