/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(project(":tptp-parser"))
    testImplementation(project(":parser"))
    testImplementation(libs.org.jetbrains.kotlin.kotlin.reflect)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    compileOnly(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    providedCompile(project(":util"))
    providedCompile(project(":theory"))
}

description = "BITNOTS :: Common :: Client SDK for the Proof Service"
