/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    providedCompile(project(":util"))
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.org.openjfx.javafx.controls)
    compileOnly(libs.org.openjfx.javafx.graphics)
    compileOnly(libs.org.openjfx.javafx.base)
}

description = "BITNOTS :: Common :: OpenJFX Utilities"
