/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    providedCompile(project(":language"))
    providedCompile(project(":theory"))
}

description = "BITNOTS :: Common :: Common Parser Classes"
