@startuml

!unquoted procedure SALT($x)
"{{
salt
%invoke_procedure("_"+$x)
}}" as $x
note top: $x
!endprocedure

!procedure _empty()
{+
{* File | Help }
{+
Source: | ^TPTP^
Version: | "1.7.0"
Location: | "/usr/local/share/tptp"
[ Fetch ]
}
}
!endprocedure

!procedure _folders()
{+
{* File | Help }
{
{S
{#
# | Name | Form
. | PRA | DIR
. | SYN | DIR
. | TOP | DIR
}
} | {#
<&trash>
<&plus>
<&pencil>
<&media-play>
}
}
}
!endprocedure

!procedure _TOP()
{+
{* File | Help }
{ [ Filter ] }
{{S
{#
# | Name | Form
. | TOP001-1.p | CNF
. | TOP001-2.p | CNF
. | TOP002-1.p | CNF
}
} | {#
<&trash>
<&plus>
<&pencil>
<&media-play>
}
}
}
!endprocedure

!procedure _filter()
{+
{
Form: | ^FOF^
}
{ [ Cancel ] | [ OK ] }
}
!endprocedure

!procedure _filtered()
{+
{* File | Help }
{ [ Filter ] | [ Clear Filters ] }
{{S
{#
# | Name | Form
. | TOP020+1.p | FOF
. | TOP021+1.p | FOF
. | TOP022+1.p | FOF
}
} | {#
<&trash>
<&plus>
<&pencil>
<&media-play>
}
}
}
!endprocedure

!procedure _new_fetch()
{+
{* File | Help }
{ [  Save File Set ] | [ Delete File Set ] }
"My name for problem set"
{S
{#
File Name | Source | Harness | Last Run
multi-selectable | TPTP | q=6 to=30 sl=5 | .
list of problem files | TPTP | q=6 to=30 sl=5 | .
}
} | {#
 <&trash>
 <&plus>
 <&pencil>
 <&media-play>
 }
{ [ Run ] | [ See History ] | [ <&lock-locked> Unlock ] }
}
!endprocedure

!procedure _unlock()
{+
{* File | Help }
{ [ Save File Set ] | [ Delete File Set ] }
"My name for problem set"
{S
{#

File Name | Source | Harness | Last Run
multi-selectable | TPTP | q=6 to=30 sl=5 | .
list of problem files | TPTP | q=6 to=30 sl=5 | .
}
} | {#
 <&trash>
 <&plus>
 <&pencil>
 <&media-play>
}
{ [ <&lock-unlocked> Save and Lock ] | [ Delete Problem ] | [ Undo ] | [ Reset ] }
}
!endprocedure

!procedure _lock_warning()
{+
Warning: A file set with this name already exists.
If you over-write that files, you will lose your record of
previous run-times and configurations.
{ [ Over-write files ] | [ Go back and rename ] }
}
!endprocedure

!procedure _run()
{+
{* File | Help }
{ [ Save File Set ] | [ Delete File Set ] }
"My name for problem set"
{S
{#
File Name | Source | Harness | Last Run
multi-selectable | TPTP | q=6 to=30 sl=5 | .
list of problem files | TPTP | q=6 to=30 sl=5 | .
}
} | {#
 <&trash>
 <&plus>
 <&pencil>
 <&media-play>
}
{ [ Run ] | [ See History ] | [ <&lock-locked> Unlock ] }
}
!endprocedure

(*) -> SALT(empty) : first run
empty -right-> SALT(folders)
folders -right-> SALT(TOP)
TOP --> SALT(filter)
filter -left-> SALT(filtered)

@enduml
