@startuml

!unquoted function SALT($x)
"{{
salt
%invoke_void_func("_"+$x)
}}" as $x
note top: $x
!endfunction

!function _empty()
{+
{* File | Help
 File | New | Open | Recent > }
{ [ Save ] | [ Delete Problem Set ] }
"No problem set selected"
{S
{#
File Name | Source | Harness | Last Run
. | . | . | .
. | . | . | .
. | . | . | .
}
}
{ [ Run ] | [ See History ] | [ <&lock-locked> Unlock ] }
}
!endfunction

!function _new()
{+
name problem set: | "My name for problem set"
source | ^tptp^
domains | ^"AGT, SYN     "^
form | ^ FOF ^
[ Fetch ]
}
!endfunction

!function _new_fetch()
{+
{* File | Help }
{ [ Save ] | [ Delete Problem Set ] }
"My name for problem set"
{S
{#
File Name | Source | Harness | Last Run
multi-selectable | TPTP | q=6 to=30 sl=5 | .
list of problem files | TPTP | q=6 to=30 sl=5 | .
}
}
{ [ Run ] | [ See History ] | [ <&lock-locked> Unlock ] }
}
!endfunction

!function _unlock()
{+
{* File | Help }
{ [ Save ] | [ Delete Problem Set ] }
"My name for problem set"
{S
{#
File Name | Source | Harness | Last Run
multi-selectable | TPTP | q=6 to=30 sl=5 | .
list of problem files | TPTP | q=6 to=30 sl=5 | .
}
}
{ [ <&lock-unlocked> Save and Lock ] | [ Delete Problem ] | [ Undo ] | [ Reset ] }
}
!endfunction

!function _lock_warning()
{+
Warning: A problem set with this name already exists.
If you over-write that files, you will lose your record of
previous run-times and configurations.
{ [ Over-write files ] | [ Go back and rename ] }
}
!endfunction

!function _run()
{+
{* File | Help }
{ [ Save ] | [ Delete Problem Set ] }
"My name for problem set"
{S
{#
File Name | Source | Harness | Last Run
multi-selectable | TPTP | q=6 to=30 sl=5 | .
list of problem files | TPTP | q=6 to=30 sl=5 | .
}
}
{ [ Run ] | [ See History ] | [ <&lock-locked> Unlock ] }
}
!endfunction

(*) -> SALT(empty) : first run
empty -right-> SALT(new)
new --> SALT(new_fetch) : require and new name
new_fetch -left-> SALT(unlock)
unlock --> SALT(lock_warning)
lock_warning -right-> SALT(run)

@enduml
