/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.micrometer.micrometer.core)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    compileOnly(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    compileOnly(libs.org.jetbrains.annotations)
}

description = "BITNOTS :: Common :: Util"
