/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":theory"))
    api(project(":prover"))
    api(project(":inference"))
    api(project(":jfx-utils"))
    api(project(":util"))
    api(project(":language"))
    api(project(":tableau"))
    api(project(":tableau-prover"))
    api(project(":tptp-parser"))
    api(project(":ipr-parser"))
    api(project(":parser"))
    api(libs.org.jetbrains.annotations)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.javafx)
    api(libs.io.micrometer.micrometer.core)
    api(libs.org.openjfx.javafx.controls)
    api(libs.org.openjfx.javafx.graphics)
    api(libs.org.openjfx.javafx.base)
    api(libs.de.jensd.fontawesomefx.commons)
    api(libs.de.jensd.fontawesomefx.fontawesome)
    api(libs.de.jensd.fontawesomefx.materialicons)
    api(libs.de.jensd.fontawesomefx.materialstackicons)
    api(libs.org.controlsfx.controlsfx)
    api(libs.com.uchuhimo.konf.core)
    api(libs.com.uchuhimo.konf.yaml)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.yaml)
}

description = "BITNOTS :: Applications :: Regression"
