/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jcenter.bintray.com/")
    }

    maven {
        url = uri("https://dl.bintray.com/kotlin/kotlinx/")
    }

    maven {
        url = uri("https://maven.atlassian.com/3rdparty/")
    }
}

group = "com.benjishults.bitnots"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
