/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.annotations)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.jetbrains.kotlin.kotlin.scripting.common)
    api(libs.org.jetbrains.kotlin.kotlin.main.kts)
    api(libs.org.jetbrains.kotlin.kotlin.scripting.jvm)
    api(libs.org.jetbrains.kotlin.kotlin.scripting.jvm.host)
    api(libs.org.jetbrains.kotlin.kotlin.script.runtime)
    api(project(":language"))
    api(project(":util"))
    api(project(":theory"))
    api(project(":tableau"))
    api(project(":prover"))
    api(project(":tableau-prover"))
    api(project(":inference"))
    api(project(":tptp-parser"))
    api(project(":parser"))
    api(libs.org.apache.commons.commons.csv)
    api(libs.io.micrometer.micrometer.core)
}

description = "BITNOTS :: Common :: Test"
