/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.reflect)
    providedCompile(project(":util"))
    providedCompile(project(":language"))
    providedCompile(project(":theory"))
}

description = "BITNOTS :: Common :: Inference"
