@startuml

hide empty description
agent "Problem Set" as problem_set
agent Harness
agent Run
agent Prover
agent Version
usecase asdf
agent Result

Run --> Prover
Run --> Harness
Run --> problem_set

Run -> Result

Prover --> Version
problem_set --> Version
Harness --> Version

@enduml
