/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.stdlib)
    compileOnly(libs.org.jetbrains.kotlin.kotlin.reflect)
    compileOnly(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    compileOnly(libs.com.fasterxml.jackson.core.jackson.annotations)
    compileOnly(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.yaml)
    providedCompile(project(":util"))
    providedCompile(project(":parser"))
    providedCompile(project(":language"))
    providedCompile(project(":prover"))
    providedCompile(project(":tableau-prover"))
    providedCompile(project(":theory"))
    providedCompile(project(":inference"))
}

description = "BITNOTS :: Common :: TPTP Parser"
